version: "3.5"

services:
  web:
    build: .
    ports:
     - "5000:8080"
    volumes:
     - ./src:/var/luasnake
     - ./config/http.conf:/etc/nginx/conf.d/http.conf
     - ./config/server.dev.conf:/etc/nginx/conf.d/server.conf