version: "3.5"

services:
  web:
    build: .
    ports:
     - "5000:5000"
    command:
     - /usr/local/openresty/bin/openresty
     - -g
     - daemon off;
    volumes:
     - ./src:/var/luasnake
     - ./config/server.dev.conf:/etc/nginx/conf.d/default.conf